platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!
swift_version = '5'

target 'Cafe' do
  pod 'SnapKit', '~> 4.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|  
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end 
  end
end 
